In [176]:
import pandas as pd
import numpy as np

In [177]:
df= pd.read_csv('C://Users//USER//Downloads//ETH_1h.csv', parse_dates=['Date'], date_format='%Y-%m-%d %I-%p')

In [181]:
df=df.set_index('Date')
df.resample('W').agg({'High':'min', 'Low':'max', 'Volume':'sum'})

              High     Low        Volume
Date
2017-07-02  257.92  284.87  8.084631e+07
2017-07-09  234.00  282.31  2.246746e+08
2017-07-16  141.70  238.00  5.017750e+08
2017-07-23  159.54  234.97  7.221637e+08
2017-07-30  181.80  229.60  2.657305e+08
...            ...     ...           ...
2020-02-16  219.63  285.10  3.912867e+08
2020-02-23  249.79  282.00  3.067838e+08
2020-03-01  214.79  274.28  3.693920e+08
2020-03-08  209.72  245.01  2.736569e+08
2020-03-15  110.99  205.83  4.983998e+08

[142 rows x 3 columns]

In [182]:
df

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                     ...     ...     ...     ...     ...         ...
2017-07-01 15:00:00  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
2017-07-01 14:00:00  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
2017-07-01 13:00:00  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
2017-07-01 12:00:00  ETHUSD  275.01  275.01  271.00  274.83   824362.87
2017-07-01 11:00:00  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 6 columns]